#
#
#
redisbroker:
    image: redis
    ports:
        - "6379:6379"

logstashshipper:
    image: logstash
    volumes:
        - ./logstash/logs:/var/logs
        - ./logstash/conf/shipper:/etc/conf  
        - ./logstash/patterns:/etc/patterns  
    links: 
        - redisbroker:redis
    command: logstash -f /etc/conf/logstash.conf

logstashindexer:
    image: logstash
    volumes:
        - ./logstash/conf/indexer:/etc/conf
    links:
        - redisbroker:redis
        - elasticsearch
    ports:
        - "5514:5514"
    command: logstash -f /etc/conf/logstash.conf

elasticsearch:
    image: elasticsearch
    volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports: 
        - "9200:9200"
        - "9300:9300"

kibana:
    image: kibana
    links:
        - elasticsearch:elasticsearch
    ports:
        - "5601:5601"
